### ISSUE TITLE
Make failed

### ISSUE THREAD

**Issue by admshao** [bazukas/obs-qtwebkit#11]
I first tried to install libqt5webkit5-dev but got error and found that is a Know bug on Ubuntu and i can only install libqt4

```
The following packages have unmet dependencies:
 libqt5webkit5-dev : Depends: qtbase5-dev
                     Depends: qtdeclarative5-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

Then,

I download Qt 5.5 from their website and installed on my home folder. Than created a symbolic link for include files into /usr/include and the same for libs into /usr/lib/

Now i`m using this Makefile https://gist.github.com/admshao/99ba99ddf4a8a3b2fe4d
and it results in this https://gist.github.com/admshao/4bd6d156cc6726779410

I dunno how to proceed.

**Comment by bazukas** [comment]
You should be able to install that package, what version of Ubuntu do you have?
And why don't you use Makefile from the repo? Yours does not link renderer to qt libs.

**Comment by admshao** [comment]
I'm using Ubuntu 15.04 directly from ubuntu website. I guess kernel version is 3.15.0-28 right now

Since 12.04 people are having problems https://bugs.launchpad.net/checkbox/+bug/1282257
Yesterday i found another bug tracker that somebody reported obs-studio also not compiling due to Missing qt5 libs. 

I tried using Makefile from repo but got that qt5 issue. Then i tried to create my own based on yours and my custom installation of Qt5.5 from .sh provide by their website. But i'm new with compiling shared libs and clearly i wasn't able.

Maybe install those libs from .deb from ppa? Is that possible?

**Comment by admshao** [comment]
I just clonned the repo and tried to add my Qt paths to Original Makefile.

I ended up with this https://gist.github.com/admshao/1c13c5cf6589920abddc
my console output https://gist.github.com/admshao/432373a526152e2e57f2

**Comment by bazukas** [comment]
What issue do you get when using Makefile from repo? You still did not link qt libs in your new makefile. You'd need to add "-lQt5WebKitWidgets -lQt5Sensors -lQt5Location -lQt5Quick -lQt5PrintSupport -lQt5OpenGL -lQt5WebKit -lQt5Positioning -lQt5Qml -lQt5Widgets -lQt5Gui -lQt5Network -lQt5Core" to LDLIBS_RENDERER

**Comment by admshao** [comment]
I cannot express how relived I am. Just adding those linking options did the trick.
The issue i got trying to use the repo Make was that Ubuntu atm has the qt5 broken under their ppa.

Thank you very much.
