### ISSUE TITLE
After restarting/crashing OBS a few times lots of idling processes

### ISSUE THREAD

**Issue by green-big-frog** [bazukas/obs-qtwebkit#12]
Thanks for your great work!

After I restarted OBS a few times or it crashed there are all these idling processes...

A screenshot of the system monitor on Ubuntu 15.04

![image](https://cloud.githubusercontent.com/assets/6208894/10417168/83dad0b0-7032-11e5-8d8f-bd42ddfa2f41.png)

**Comment by bazukas** [comment]
Thank for the report. Latest update should fix the problem.

**Comment by bazukas** [comment]
Is your problem resolved? If so, please close the issue.

**Comment by green-big-frog** [comment]
I haven't had time to really test it... I'll test it right now!

**Comment by green-big-frog** [comment]
So far it seams to be working! Thanks!
