### ISSUE TITLE
Make won't work

### ISSUE THREAD

**Issue by StillAliveGames** [bazukas/obs-qtwebkit#13]
On my computer the `make`-command won't work: 
LOG:
```
g++ -c -std=c++11 -Wall -g -fPIC -I/usr/include/obs -I./src -I/usr/include/x86_64-linux-gnu/qt5/QtWebKitWidgets -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWebKit -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/x86_64-linux-gnu/qt5  src/qtwebkit-main.cpp -o build/qtwebkit-main.o
src/qtwebkit-main.cpp: In function ‘bool obs_module_load()’:
src/qtwebkit-main.cpp:153:22: error: invalid conversion from ‘const char* (*)(void*)’ to ‘const char* (*)()’ [-fpermissive]
  info.get_name       = qtwebkit_get_name;
                      ^
Makefile:55: recipe for target 'build/qtwebkit-main.o' failed
make: *** [build/qtwebkit-main.o] Error 1
```

**Comment by bazukas** [comment]
What is version of obs that you compile against?

**Comment by StillAliveGames** [comment]
Where can i see that?

**Comment by StillAliveGames** [comment]
Oh... I found it: 0.11.2(Linux)

**Comment by bazukas** [comment]
Yes, obs api has been slightly changed since then, you should consider upgrading to 0.12 (+ you'll get many improvements for obs as well).

**Comment by StillAliveGames** [comment]
How can I do that? The "Search for Updates"-Function won't do anything and the Update-Manager showed nothing

**Comment by StillAliveGames** [comment]
(using Ubuntu 14.10 64-Bit)

**Comment by bazukas** [comment]
I assume that you installed from official ppa repository. It seems like obs package for 14.10 is outdated for some reason. I'm currently inquiring why that is so.

Meanwhile, if you are adventurous, you can try installing unstable version from ppa:obsproject/obs-studio-unstable or just upgrading to 15.04.

**Comment by StillAliveGames** [comment]
Ok I'll try! Thx for the fast support!

**Comment by bazukas** [comment]
It seems like they can't push updates for 14.10 repo because it is no longer supported, so the only ways for you to upgrade your obs is to either compile it yourself or upgrade Ubuntu to 15.04.
