### ISSUE TITLE
Can't load mjpeg stream

### ISSUE THREAD

**Issue by TheTonon** [bazukas/obs-qtwebkit#22]
So, I have that Android app that gives me a mjpeg video stream and I want to load it, but can't since obs-qtwebkit can't load the video correctly. I'm trying to read the docs to find a solution and push it, but without success since idk anything of qt.

Is there a workaround?? I know the Mac Browser Source works flawlessly, but I can't find the source for it.

**Comment by bazukas** [comment]
Did you try using media source instead?

**Comment by TheTonon** [comment]
It really does the job. I didn't even need the plugin... Thanks for the help.
