### ISSUE TITLE
Bus Error with Multiple sources

### ISSUE THREAD

**Issue by chrsdion** [bazukas/obs-qtwebkit#3]
I'm getting a bus error with multiple plugin sources running. It causes OBS to crash immediately on start up. What log files do you need to research?

**Comment by bazukas** [comment]
I submitted a possible fix, please check and let me know if it helped.

**Comment by chrsdion** [comment]
Will do! Thanks for the quick update. I'll give it some testing tonight.

**Comment by chrsdion** [comment]
So I did some testing last night and I was able to restart OBS ok but I had to open the properties on the source and update the web address to get the plugin to work after obs restart.

**Comment by bazukas** [comment]
So you have to do that every time you start up obs? Could you, please, execute "ps aux | grep renderer" and include the results?

**Comment by chrsdion** [comment]
Finally got around to testing again. Looks like itr was something with my system. I've got it running fine on Kubuntu 15.04. It doesn't crash when opening OBS anymore. I'll be using it quite a bit so if I run across anything I'll let you know.

Thanks so much for building this.

This issue can be closed.
